site_name: BIM Kompendium
site_url: https://cadwork-bim.readthedocs.io/de/latest/
site_author: Michael Brunner
theme:
    name: material
    nav_style: dark
    logo: cw_logo.svg
    version: v28
    palette:
    - scheme: default
      toggle:
        name: Switch to light mode
        icon: material/weather-sunny
    - scheme: slate
      #primary: grey
      #accent: blue
      toggle:
        name: Switch to dark mode
        icon: material/weather-night
    features:
    - content.code.annotate
    # - content.tabs.link
    # - header.autohide
    # - navigation.expand
    # - navigation.indexes
    # - navigation.instant
    # - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    # - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
markdown_extensions:
  - attr_list  
  - admonition
  - toc:
      permalink: false
  - meta
  - pymdownx.keys
  - footnotes:
      SEPARATOR: _footnote_
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - stylesheets\extra.css


extra:
  generator: false
  copyright: Copyright & copy; 2021 cadwork
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Brunner246
      name: BIM_Kompendium
  alternate:
    - name: Deutsch
      link: ./de/
      lang: de
    - name: Français
      link: ./fr/
      lang: fr
    - name: English
      link: ./en/
      lang: en
  analytics:
    provider: google
    property: G-MT51DC3GS2
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          datas: 1
          note:
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          datas: 0
          note:
            Thanks for your feedback!
  consent:
    title: Cookie consent
    description: 
      Wir verwenden Cookies, um die Effektivität unserer Dokumentation zu messen und um festzustellen, ob Sie
      finden, wonach sie suchen. Mit Ihrer Zustimmung helfen Sie uns, unsere
      unsere Dokumentation zu verbessern.
    

plugins:
  - pdf-export:
      verbose: true
      media_type: print
      enabled_if_env: ENABLE_PDF_EXPORT #  (set environment variable ENABLE_PDF_EXPORT to 1 to enable)

  - search:
      separator: '[\s\-\.\_]+'  
  #- mkdocs-versioning:
      #version: "Version 29" 
  # - mkdocs-versioning:
      # version: version 28.0
  - i18n:
      default_language: de
      #default_language: !ENV [DEFAULT_LANGUAGE, "de"]
      #default_language_only: !ENV [DEFAULT_LANGUAGE_ONLY, false]
      languages:
        de: Deutsch
        fr: Français   
        en: English 
      nav_translations:
        fr:
          1.Import: 1.Import
          2.Modellierung: 2.Modélisation
          3.Export: 3.Export
          4.BCF: 4.BCF
          5.Beispiele: 5.Exemples
          6.Workflowsheets: 6.Workflowsheets
          7.Über: 7.À propos de nous
        en:
          1.Import: 1.Import
          2.Modellierung: 2.Modelling
          3.Export: 3.Export
          4.BCF: 4.BCF
          5.Beispiele: 5.Examples
          6.Workflowsheets: 6.Workflowsheets
          7.Über: 7.About
