site_name: BIM Kompendium
site_url: https://cadwork.bim_kompendium.swiss/

theme:
    name: material
    nav_style: dark
    logo: cw_logo.svg
    version: v28
    palette:
    - scheme: default
      toggle:
        name: Switch to light mode
        icon: material/weather-sunny
    - scheme: slate
      #primary: grey
      #accent: blue
      toggle:
        name: Switch to dark mode
        icon: material/weather-night
    features:
    - search.suggest
    - search.highlight
    #- navigation.tabs
    #- navigation.tabs.sticky
    #- navigation.instant
markdown_extensions:
  - attr_list  
  - admonition
  - toc:
      permalink: false
  - meta
  - pymdownx.keys
  - footnotes:
      SEPARATOR: _footnote_
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - stylesheets\extra.css
     
extra:
  generator: false
  copyright: Copyright & copy; 2021 cadwork
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Brunner246
      name: BIM_Kompendium
  alternate:
    #- name: Default (de)
      #link: ./
      #lang: de
    - name: Deutsch
      link: ./de/
      lang: de
    - name: Français
      link: ./fr/
      lang: fr

plugins:
  - search:
      separator: '[\s\-\.\_]+'  
  - mkdocs-versioning:
      version: version 28.0
    
  - i18n:
      # default_language: !ENV [DEFAULT_LANGUAGE, "de"]
      # default_language_only: !ENV [DEFAULT_LANGUAGE_ONLY, false]
      default_language: de
      languages:
        de: Deutsch
        fr: Français    
      nav_translations:
        fr:
          3.BCF: 3.BCFé
          4.Beispiele: 4.examplé  
          2.Export: 2.Exporté
          1.Import: 1.Importé
          5.Workflowsheets: 5.Workflowsheets
