site_name: BIM Kompendium
site_url: https://cadwork.bim_kompendium.swiss/
nav:
    - BuildingInformationModeling: index.md
    - IFC & cadwork: ifc.md
    - BCF & cadwork: bcf.md
    - Examples: examples.md
    - About: about.md
theme:
    name: material
    nav_style: dark
    logo: logo_small.png
    version: v28
    palette:
    - scheme: default
      toggle:
        name: Switch to light mode
        icon: material/weather-sunny
    - scheme: slate
      #primary: grey
      #accent: blue
      toggle:
        name: Switch to dark mode
        icon: material/weather-night
    features:
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
markdown_extensions:
  - attr_list  
  - admonition
  - meta
  - pymdownx.keys
  - footnotes:
      SEPARATOR: _footnote_
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
extra_css:
  - stylesheets\extra.css
plugins:
  - search:
      separator: '[\s\-\.\_]+'  
  - mermaid2:
        arguments:
          theme: 'light'   
  #git-revision-date-localized:
      #type: datetime
  #- mkdocs-versioning:
      #version: 0.9.0                 
extra:
  generator: false
  copyright: Copyright &copy; 2021 cadwork
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Brunner246
      name: BIM_Kompendium
extra_javascript:
    - https://unpkg.com/mermaid/dist/mermaid.min.js